### ISSUE TITLE
Download Accelerator?

### ISSUE THREAD

**Issue by USBhost** [USBhost/build-tools-gcc#12]
Do we really want download accelerators like https://github.com/axel-download-accelerator/axel?
'wget' worked just fine in the past and if you were to need an accelerator to download gcc etc.. then I think you have other problems.

**Comment by USBhost** [comment]
@nathanchance Am I missing a reason why we need to use it?

**Comment by nathanchance** [comment]
I have no strong opinion. @MSF-Jarvis has spoken highly of it and I figured if we were looking to speed up the process with parallel compression binaries, might as well go all the way; it's a small binary and quick to build.

If you feel it's worth removing, I am not going to fight you haha, it's your project.

**Comment by msfjarvis** [comment]
`axel` with 10 threads downloads things atleast 4 times faster than `wget` for me, but yes the difference makes more sense with larger files only, like kernel and GCC tarballs.
