### ISSUE TITLE
https won't connect

### ISSUE THREAD

**Issue by ac130kz** [USBhost/build-tools-gcc#13]
ISL is failing to download for me, unless http is specified instead of https in this line:
`https://isl.gforge.inria.fr/${ISL}.tar.xz`

**Comment by krasCGQ** [comment]
You can make a PR fixing that issue.

**Comment by ac130kz** [comment]
https://github.com/USBhost/build-tools-gcc/pull/14/commits/164adde9139676b51649b1c33fdbff64967395d3
