### ISSUE TITLE
Error build: libsanitizer_common.a

### ISSUE THREAD

**Issue by ACherepkov1989** [USBhost/build-tools-gcc#24]
Hi! 
I am using Ubuntu 16.04.
Packages installed: `$ sudo apt-get install flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev libgcc1:i386 bc libcloog-isl-dev libcap-dev autoconf libgmp-dev build-essential gcc-multilib g++-multilib pkg-config libmpc-dev libmpfr-dev autopoint gettext liblzma-dev libssl-dev libz-dev`

What additional package do I need to install?
Error build: `libtool: link: /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ranlib .libs/libsanitizer_common.a
/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ranlib: .libs/libsanitizer_common.a: No space left on device
Makefile:434: ошибка выполнения рецепта для цели «libsanitizer_common.la»
make[4]: *** [libsanitizer_common.la] Ошибка 1
make[4]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libsanitizer/sanitizer_common»
Makefile:467: ошибка выполнения рецепта для цели «all-recursive»
make[3]: *** [all-recursive] Ошибка 1
make[3]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libsanitizer»
Makefile:337: ошибка выполнения рецепта для цели «all»
make[2]: *** [all] Ошибка 2
make[2]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libsanitizer»
Makefile:12107: ошибка выполнения рецепта для цели «all-target-libsanitizer»
make[1]: *** [all-target-libsanitizer] Ошибка 2
make[1]: *** Ожидание завершения заданий…
mv -f .deps/method-ml.Tpo .deps/method-ml.Plo
/bin/bash ./libtool --tag=CC   --mode=link /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/./gcc/xgcc -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/./gcc/ -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/lib/ -isystem /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/include -isystem /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/sys-include    -ftls-model=initial-exec -Wall -Werror  -Wc,-pthread -g -O2   -Wl,-O1    -o libitm.la -version-info 1:0:0 -Wl,--version-script,../../../gcc/libitm/libitm.map -rpath /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/lib/../lib64 aatree.lo alloc.lo alloc_c.lo alloc_cpp.lo barrier.lo beginend.lo clone.lo eh_cpp.lo local.lo query.lo retry.lo rwlock.lo useraction.lo util.lo sjlj.lo tls.lo method-serial.lo method-gl.lo method-ml.lo   futex.lo  
libtool: link: /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/./gcc/xgcc -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/./gcc/ -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ -B/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/lib/ -isystem /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/include -isystem /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/sys-include    -shared  -fPIC -DPIC  .libs/aatree.o .libs/alloc.o .libs/alloc_c.o .libs/alloc_cpp.o .libs/barrier.o .libs/beginend.o .libs/clone.o .libs/eh_cpp.o .libs/local.o .libs/query.o .libs/retry.o .libs/rwlock.o .libs/useraction.o .libs/util.o .libs/sjlj.o .libs/tls.o .libs/method-serial.o .libs/method-gl.o .libs/method-ml.o .libs/futex.o    -pthread -Wl,-O1 -Wl,--version-script -Wl,../../../gcc/libitm/libitm.map   -Wl,-soname -Wl,libitm.so.1 -o .libs/libitm.so.1.0.0
libtool: link: (cd ".libs" && rm -f "libitm.so.1" && ln -s "libitm.so.1.0.0" "libitm.so.1")
libtool: link: (cd ".libs" && rm -f "libitm.so" && ln -s "libitm.so.1.0.0" "libitm.so")
libtool: link: /mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ar rc .libs/libitm.a  aatree.o alloc.o alloc_c.o alloc_cpp.o barrier.o beginend.o clone.o eh_cpp.o local.o query.o retry.o rwlock.o useraction.o util.o sjlj.o tls.o method-serial.o method-gl.o method-ml.o futex.o
/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/aarch64-linux-gnu/aarch64-linux-gnu/bin/ar: .libs/libitm.a: No space left on device
Makefile:478: ошибка выполнения рецепта для цели «libitm.la»
make[4]: *** [libitm.la] Ошибка 1
make[4]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libitm»
Makefile:725: ошибка выполнения рецепта для цели «all-recursive»
make[3]: *** [all-recursive] Ошибка 1
make[3]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libitm»
Makefile:390: ошибка выполнения рецепта для цели «all»
make[2]: *** [all] Ошибка 2
make[2]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc/aarch64-linux-gnu/libitm»
Makefile:16033: ошибка выполнения рецепта для цели «all-target-libitm»
make[1]: *** [all-target-libitm] Ошибка 2
make[1]: выход из каталога «/mnt/d53988f0-c01b-4f39-b941-4aa0d973a0e8/android/toolchain/build-tools-gcc/build-gcc»
Makefile:901: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2 
Error while compiling final toolchain!`

**Comment by USBhost** [comment]
You hit an out of space error. How much free space do you have on your drive? If you have plenty then retry it with this option --no-tmpfs or -nt

**Comment by ACherepkov1989** [comment]
@USBhost, thank you, the compiler gathered.
I allocated 4 GB of RAM, it used to be enough.
