### ISSUE TITLE
Issue with building linux headers

### ISSUE THREAD

**Issue by jetonbacaj** [USBhost/build-tools-gcc#29]
Hello,

There is an issue with building the linux headers;

> ============================
> ==  MAKING LINUX HEADERS  ==
> ============================
> 
> make: *** No rule to make target 'headers_install'.  Stop.
> 
> Error while building/installing Linux headers!

Looking at the `linux` directory at the root level, it is empty.

Full output is here; https://pastebin.com/r5mHEfbB

Using Lubuntu 18.04LTS.

Let me know what other information I can supply.

**Comment by krasCGQ** [comment]
Can I get the output of `ls -s sources | grep tar`?
Something (particularly Linux one) might have been corrupted or not downloaded correctly.

**Comment by krasCGQ** [comment]
Oh...wait:
```
pxz: execution of xz binary failed: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

Before doing what I said above, do you have `xz` installed?

**Comment by flipflop133** [comment]
the problem comes from recent changes in  this git :
https://github.com/jnovy/pxz/commits/master
the commits from the 7 may are broken the script so I just revert the commit and I'm using my own pxz cloned git for now, in hope of a better fix.
So just replace at line 364 with this repo for now : https://github.com/francois133/PXZ

**Comment by krasCGQ** [comment]
```
gcc (master) 〉PATH=$(pwd)/prebuilts/bin:${PATH} pxz --version
Parallel PXZ 4.999.9beta (build 20190511)
pxz: execution of xz binary failed: No such file or directory
```

Oh well...

**Comment by krasCGQ** [comment]
Reverted a commit from PXZ upstream that seems to break the binary's sanity, testing...
