### ISSUE TITLE
Currently fails to build because of ISL.

### ISSUE THREAD

**Issue by USBhost** [USBhost/build-tools-gcc#3]
To fix future problems like this I will only use git for gcc and kernel. Everything else I will be using tarballs.
Note however this will need more maintenance.

**Comment by krasCGQ** [comment]
The interesting thing is that the build only fails for GCC fetched from git. 7.3.0 and 8.1.0 tarballs remain unaffected.

At ISL side, it needs a few reverts to make build work again.
