### ISSUE TITLE
building axel is broken on Arch based distros

### ISSUE THREAD

**Issue by flipflop133** [USBhost/build-tools-gcc#32]
New commits to axel git (https://github.com/axel-download-accelerator/axel) are broking building.

**Comment by flipflop133** [comment]
temporary fix : installing axel community package.

**Comment by flipflop133** [comment]
make: *** No targets specified and no makefile found.  Stop.

Error building axel!

**Comment by flipflop133** [comment]
https://github.com/axel-download-accelerator/axel/commit/b67e5eeae8b4c560704b4d0f4449fdd079922eff
seems to be linked to this commit

**Comment by USBhost** [comment]
arch linux?

**Comment by flipflop133** [comment]
yes (Manjaro)

**Comment by USBhost** [comment]
```
./configure: line 7386: syntax error near unexpected token `LIBS="$PTHREAD_LIBS $LIBS"'
./configure: line 7386: `LIBS="$PTHREAD_LIBS $LIBS"'
make: *** No targets specified and no makefile found.  Stop.
```


Now that's interesting

**Comment by USBhost** [comment]
do people not check syntax errors...

**Comment by krasCGQ** [comment]
According to comments on commit above, someone suggested installing `autoconf-archive` package.

Can't really test that suggestion since I'm busy with working on my near-deadline tasks.

**Comment by USBhost** [comment]
I'll do that in the morning

**Comment by RogerF81** [comment]
Same here on Ubuntu unfortunately :/

**Comment by USBhost** [comment]
yep `autoconf-archive` fixed it

**Comment by USBhost** [comment]
However do you guys on arch linux have that?

**Comment by krasCGQ** [comment]
https://www.archlinux.org/packages/community/any/autoconf-archive/

**Comment by USBhost** [comment]
Then might as well just install axel from the community. No need to build it.

**Comment by flipflop133** [comment]
So I close the issue thread with the issue still present?

**Comment by USBhost** [comment]
I'll leave it open for a while to see if anyone wants to add in anything. This building problem is an easy fix for Ubuntu. However not for Arch based distros.
