### ISSUE TITLE
Error while compiling final toolchain!

### ISSUE THREAD

**Issue by flipflop133** [USBhost/build-tools-gcc#35]
../../../../../gcc/libstdc++-v3/src/c++98/strstream.cc: In member function ‘virtual void std::istrstream::_ZTv0_n24_NSt10istrstreamD1Ev()’:
../../../../../gcc/libstdc++-v3/src/c++98/strstream.cc:417:1: internal compiler error: in aarch64_return_address_signing_enabled, at config/aarch64/aarch64.c:4865
  417 | } // namespace
      | ^

I tried yesterday and now and I'm getting this everytime, I guess we need a new patch @krasCGQ  lol.

**Comment by USBhost** [comment]
What GCC version were you building?

**Comment by flipflop133** [comment]
version 10 for arm64
(./build -a arm64 -s gnu -v 10)

**Comment by USBhost** [comment]
Well since you are building experimental, build errors do happen. "internal compiler error" does sound like it But that's just me.

**Comment by flipflop133** [comment]
They fixed it, I tested and it's now compiling.
Sorry for disturbing.

https://github.com/gcc-mirror/gcc/commit/24c1fa60e50bad01731798f79d2732bf21e0addb
