### ISSUE TITLE
Buiding axel fails on ubuntu 19.04

### ISSUE THREAD

**Issue by libxzr** [USBhost/build-tools-gcc#37]
log:
Clean up successful! Already up to date. ./build: line 346: ./autogen.sh: No such file or directory ./build: line 347: ./configure: No such file or directory make: *** No targets specified and no makefile found. Stop. [01;31mError building axel![0m

The temporary solution is `sudo apt-get install axel`

**Comment by USBhost** [comment]
Install autoconf-archive

**Comment by libxzr** [comment]
@USBhost `autoconf-archive is already the newest version (20180313-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

It doesnt seem like a correct fix for it.

**Comment by USBhost** [comment]
Huh... Ok. Thanks for the report... 
Axel has gone again and broke things...

**Comment by USBhost** [comment]
Should be fixed now
