### ISSUE TITLE
Can't build gnu 10 for ARM

### ISSUE THREAD

**Issue by Jprimero15** [USBhost/build-tools-gcc#41]
here is the log: 
https://del.dog/eforazakab

**Comment by USBhost** [comment]
Looking into it.

**Comment by Jprimero15** [comment]
great. Thanks

Some additional info: 
OS: Ubuntu 18.04
* I compiled gnu 9 ARM and it compiled fine.

**Comment by Jprimero15** [comment]
Up

**Comment by USBhost** [comment]
@Jprimero15 for now just remove lines 577-579
https://github.com/USBhost/build-tools-gcc/blob/master/build#L577
https://github.com/USBhost/build-tools-gcc/blob/master/build#L578
https://github.com/USBhost/build-tools-gcc/blob/master/build#L579

**Comment by USBhost** [comment]
I found the problem. The fix will be up tomorrow.

**Comment by Jprimero15** [comment]
Thanks

**Comment by USBhost** [comment]
Fixed
