### ISSUE TITLE
libcloog-isl-dev isn't available on ubuntu 19.04

### ISSUE THREAD

**Issue by infus38** [USBhost/build-tools-gcc#43]
Hi sir. Following your step "Core developer", there is a missing packages.
` libcloog-isl-dev is not available, but is referred to by another package.`

**Comment by USBhost** [comment]
Thanks for the report

**Comment by krasCGQ** [comment]
@infus38 but still builds GCC 4.9 just fine, no?

As we don't longer use CLooG in the build script for years probably we can just remove it from `README.md`.

**Comment by krasCGQ** [comment]
https://packages.ubuntu.com/search?keywords=cloog&searchon=names

It's no longer available on Eoan.

**Comment by infus38** [comment]
> @infus38 but still builds GCC 4.9 just fine, no? 

Sorry for the delay. Yes it's
