### ISSUE TITLE
Missing or wrong include directory in final build

### ISSUE THREAD

**Issue by GreyMonkey56** [USBhost/build-tools-gcc#6]
-o build/genautomata.o ../../gcc/gcc/genautomata.c
/data1/Toolchain/build-tools-gcc/build-gcc/./prev-gcc/xg++ -B/data1/Toolchain/build-tools-gcc/build-gcc/./prev-gcc/ -B/data1/Toolchain/build-tools-gcc/x86_64-linux-gnu/x86_64-linux-gnu/bin/ -nostdinc++ -B/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/src/.libs -B/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/libsupc++/.libs  -I/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/include/x86_64-linux-gnu  -I/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/include  -I/data1/Toolchain/build-tools-gcc/gcc/libstdc++-v3/libsupc++ -L/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/src/.libs -L/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/libsupc++/.libs -c   -g -O2 -gtoggle -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -fno-PIE -I. -Ibuild -I../../gcc/gcc -I../../gcc/gcc/build -I../../gcc/gcc/../include  -I../../gcc/gcc/../libcpp/include  \
        -o build/genemit.o ../../gcc/gcc/genemit.c
In file included from ../../gcc/gcc/genautomata.c:116:0:
/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/include/math.h:65:12: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration
 using std::isinf;
            ^~~~~
In file included from /usr/include/features.h:378:0,
                 from /usr/include/stdio.h:27,
                 from ../../gcc/gcc/system.h:46,
                 from ../../gcc/gcc/genautomata.c:108:
/usr/include/bits/mathcalls.h:201:1: note: previous declaration ‘int isinf(double)’
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from ../../gcc/gcc/genautomata.c:116:0:
/data1/Toolchain/build-tools-gcc/build-gcc/prev-x86_64-linux-gnu/libstdc++-v3/include/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
 using std::isnan;
            ^~~~~
In file included from /usr/include/features.h:378:0,
                 from /usr/include/stdio.h:27,
                 from ../../gcc/gcc/system.h:46,
                 from ../../gcc/gcc/genautomata.c:108:
/usr/include/bits/mathcalls.h:234:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
Makefile:2595: recipe for target 'build/genautomata.o' failed
make[3]: *** [build/genautomata.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm fsf-funding.pod gcov.pod gpl.pod cpp.pod gfdl.pod gcc.pod gcov-dump.pod gcov-tool.pod
make[3]: Leaving directory '/data1/Toolchain/build-tools-gcc/build-gcc/gcc'
Makefile:4596: recipe for target 'all-stage2-gcc' failed
make[2]: *** [all-stage2-gcc] Error 2
make[2]: Leaving directory '/data1/Toolchain/build-tools-gcc/build-gcc'
Makefile:26192: recipe for target 'stage2-bubble' failed
make[1]: *** [stage2-bubble] Error 2
make[1]: Leaving directory '/data1/Toolchain/build-tools-gcc/build-gcc'
Makefile:941: recipe for target 'all' failed
make: *** [all] Error 2

Error while compiling final toolchain!

/usr/include/features.h:378:0, <== fall back to hosts gcc compiler features, means wrong reference to
       "x86_64") TARGET="x86_64-linux-gnu" ;;
build directory for features.h inclusion

**Comment by USBhost** [comment]
what gcc version are you building?
post your command

**Comment by GreyMonkey56** [comment]
./build -a x86_64 -s gnu -v 7
with
gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]

That is: I want to test a newer toolchain for a problem I encountered.

**Comment by USBhost** [comment]
Since you were building (GCC4.8) out of the range of the support of this script. Closing as wont fix

**Comment by USBhost** [comment]
Since you were building (GCC4.8) out of the range of the support of this script. Closing as wont fix
